export interface CakeType {
  id: string;
  name: string;
  emoji: string;
  category: string;
  description: string;
  characteristics: string[];
  scienceNote: string;
  color: string;
  examples: string[];
  baseFormula: { name: string; amount: number }[];
  recipes: CakeRecipe[];
}

export interface CakeRecipe {
  name: string;
  emoji: string;
  description: string;
  group?: string;
  source?: string;          // e.g. "New York Cake Book, 1904"
  leaveningNote?: string;   // Historical leavening note (cream of tartar + soda → modern baking powder)
  optionalAdditions?: { name: string; amount: number; note: string }[]; // Modern suggestions
  ingredients: { name: string; amount: number }[];
}

// ─────────────────────────────────────────────────────────────
// ALL RECIPES: Public domain pre-1928 sources
//
// Primary source: "The New York Cake Book: Fifty Recipes by a
//   Famous New York Chef" (New York: C.A. Montgomery & Co., 1904)
//   Project Gutenberg #65572 — 100% public domain
//
// Secondary source: "The Boston Cooking-School Cook Book"
//   by Fannie Merritt Farmer, 1910 revision of 1896 original
//   Project Gutenberg #65061 — 100% public domain
//
// Measurements converted to grams:
//   1 lb = 453g | 1 oz = 28g | 1 cup flour ≈ 120g | 1 cup sugar ≈ 200g
//   1 cup butter ≈ 227g | 1 cup liquid ≈ 240ml | 1 teacup ≈ 240ml
//   1 gill = ½ cup ≈ 120ml | 1 qt ≈ 960ml | 1 pt ≈ 480ml
//   1 tsp ≈ 5g (baking powder/soda) | cream of tartar 1 tsp ≈ 3g
//
// Leavening conversions shown in leaveningNote.
// Optional modern additions shown in optionalAdditions.
// ─────────────────────────────────────────────────────────────

export const cakeTypes: CakeType[] = [
  {
    id: 'butter',
    name: 'Butter Cake',
    emoji: '🧈',
    category: 'Classic',
    description: 'Made with creamed butter and sugar — the gold standard of classic cake baking.',
    characteristics: ['Rich', 'Dense to medium', 'Butter flavor'],
    examples: ['Pound Cake', 'White Cake', 'Silver Cake', 'Golden Cake'],
    scienceNote: 'Creaming butter traps air bubbles that expand during baking, creating lift and tenderness.',
    color: 'from-yellow-400 to-amber-500',
    baseFormula: [
      { name: 'All-Purpose Flour', amount: 453 },
      { name: 'Granulated Sugar', amount: 453 },
      { name: 'Unsalted Butter', amount: 340 },
      { name: 'Whole Egg (large)', amount: 400 },
    ],
    recipes: [
      {
        group: 'Pound Cakes',
        name: 'Pound Cake No. 1',
        emoji: '🟡',
        source: 'New York Cake Book, 1904',
        description: 'The original American pound cake — one pound each of sugar, butter, eggs, and flour. Rich, dense, and timeless.',
        leaveningNote: 'Original recipe uses no leavening — rises purely from beaten eggs. For a slightly lighter crumb, modern bakers may add 1 tsp baking powder (4g).',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original — adds warmth' },
          { name: 'Salt', amount: 3, note: 'Not in original — enhances flavor' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 340 },
          { name: 'Whole Egg (large)', amount: 400 },
          { name: 'All-Purpose Flour', amount: 453 },
          { name: 'Lemon Extract', amount: 5 },
        ],
      },
      {
        group: 'Pound Cakes',
        name: 'Pound Cake No. 2 (Currant)',
        emoji: '🍇',
        source: 'New York Cake Book, 1904',
        description: 'A classic pound cake enriched with currants and warm spices — a Sunday cake from Victorian America.',
        leaveningNote: 'No chemical leavening in the original. The beaten eggs provide lift. Modern equivalent: add ½ tsp baking powder (2g) for a lighter texture.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original — pairs well with the spices' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 340 },
          { name: 'Whole Egg (large)', amount: 500 },
          { name: 'All-Purpose Flour', amount: 453 },
          { name: 'Dried Currants', amount: 80 },
          { name: 'Mace', amount: 2 },
          { name: 'Nutmeg', amount: 2 },
        ],
      },
      {
        group: 'White & Silver Cakes',
        name: 'White Cake (Silver Cake)',
        emoji: '⬜',
        source: 'New York Cake Book, 1904',
        description: 'An elegant white cake using only egg whites — produces a pure, snowy crumb. Traditionally paired with white vanilla icing.',
        leaveningNote: 'Original uses no leavening — the whites carry all the lift. Modern equivalent: add 1 tsp baking powder (4g) for extra height.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 6, note: 'Not in original — greatly improves flavor' },
          { name: 'Salt', amount: 2, note: 'Not in original — balances sweetness' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Egg White', amount: 300 },
          { name: 'All-Purpose Flour', amount: 340 },
          { name: 'Almond Extract', amount: 3 },
        ],
      },
      {
        group: 'White & Silver Cakes',
        name: 'Delicate Cake',
        emoji: '🕊️',
        source: 'New York Cake Book, 1904',
        description: 'A light, refined cake using only egg whites and sweet milk — a Victorian dinner party staple.',
        leaveningNote: 'Original uses cream of tartar (3g) + baking soda (2g) — equivalent to about 1½ tsp baking powder (6g).',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original — recommended addition' },
          { name: 'Salt', amount: 2, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Granulated Sugar', amount: 400 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'Egg White', amount: 150 },
          { name: 'Cream of Tartar', amount: 3 },
          { name: 'Baking Soda', amount: 2 },
          { name: 'All-Purpose Flour', amount: 360 },
        ],
      },
      {
        group: 'Egg-Yolk Cakes',
        name: 'Golden Cake',
        emoji: '✨',
        source: 'New York Cake Book, 1904',
        description: 'A spectacular golden cake built on 16 egg yolks, flavored with lemon and mace. Rich, tender, and deeply yellow.',
        leaveningNote: 'Original uses baking powder (10g). This is one of the few 1904 recipes already using modern leavening.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original — optional' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 340 },
          { name: 'Egg Yolk', amount: 320 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'All-Purpose Flour', amount: 907 },
          { name: 'Lemon Zest', amount: 8 },
          { name: 'Lemon Juice', amount: 20 },
          { name: 'Mace', amount: 3 },
          { name: 'Baking Powder', amount: 10 },
        ],
      },
      {
        group: 'Flavored Butter Cakes',
        name: 'Lemon Cake No. 1',
        emoji: '🍋',
        source: 'New York Cake Book, 1904',
        description: 'A bright, lemony butter cake with a clean citrus finish — lemon zest and juice in the batter.',
        leaveningNote: 'Original uses baking soda (5g) — modern equivalent is about 1 tsp baking powder (4g) or keep the soda with buttermilk.',
        optionalAdditions: [
          { name: 'Salt', amount: 3, note: 'Not in original — add to taste' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 600 },
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'Whole Egg (large)', amount: 250 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'All-Purpose Flour', amount: 480 },
          { name: 'Lemon Zest', amount: 12 },
          { name: 'Lemon Juice', amount: 30 },
        ],
      },
      {
        group: 'Flavored Butter Cakes',
        name: 'Orange Layer Cake',
        emoji: '🍊',
        source: 'New York Cake Book, 1904',
        description: 'A three-layer orange cake from 1904 New York — baked thin in jelly-cake pans and filled with fresh orange icing.',
        leaveningNote: 'Original uses baking powder (8g) — already the modern form.',
        optionalAdditions: [
          { name: 'Salt', amount: 3, note: 'Not in original' },
          { name: 'Vanilla Extract', amount: 4, note: 'Not in original — optional' },
        ],
        ingredients: [
          { name: 'All-Purpose Flour', amount: 437 },
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'Whole Egg (large)', amount: 250 },
          { name: 'Baking Powder', amount: 8 },
          { name: 'Lemon Zest', amount: 5 },
          { name: 'Orange Zest', amount: 12 },
        ],
      },
      {
        group: 'Flavored Butter Cakes',
        name: 'Almond Cake',
        emoji: '🌸',
        source: 'New York Cake Book, 1904',
        description: 'A dense, moist almond cake built on ground sweet almonds and a full pound each of sugar and flour. Rich almond flavor throughout.',
        leaveningNote: 'No chemical leavening — relies entirely on the beaten eggs. For a lighter result: add 1 tsp baking powder (4g).',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 4, note: 'Not in original — pairs well with almond' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Whole Egg (large)', amount: 400 },
          { name: 'All-Purpose Flour', amount: 453 },
          { name: 'Almonds (sliced)', amount: 80 },
          { name: 'Almond Extract', amount: 3 },
        ],
      },
      {
        group: 'Yellow Butter Cakes',
        name: 'Classic Yellow Butter Cake',
        emoji: '💛',
        source: 'Classic American recipe',
        description: 'The definitive American yellow butter cake — rich with egg yolks for color and flavor, creamed butter and sugar for tenderness, with milk alternated in for a smooth, even crumb. The foundation for countless layer cakes.',
        leaveningNote: 'Uses 2½ tsp baking powder (10g). The egg yolks add richness and structure alongside the leavening.',
        ingredients: [
          { name: 'All-Purpose Flour', amount: 300 },
          { name: 'Baking Powder', amount: 10 },
          { name: 'Salt', amount: 3 },
          { name: 'Unsalted Butter', amount: 170 },
          { name: 'Granulated Sugar', amount: 350 },
          { name: 'Egg Yolk', amount: 80 },
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'Vanilla Extract', amount: 15 },
          { name: 'Whole Milk', amount: 240 },
        ],
      },
      {
        group: 'Flavored Butter Cakes',
        name: 'Nut Cake (Hickory or Walnut)',
        emoji: '🥜',
        source: 'New York Cake Book, 1904',
        description: 'A simple, honest nut cake from 1904 — made with hickory nuts or walnuts, coffee sugar, and sweet milk. Tender and warmly flavored.',
        leaveningNote: 'Original uses cream of tartar (3g) + baking soda (2g) — equivalent to 1 tsp baking powder (4g).',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 4, note: 'Not in original — adds warmth' },
          { name: 'Salt', amount: 2, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Brown Sugar (Light)', amount: 300 },
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Whole Egg (large)', amount: 150 },
          { name: 'Whole Milk', amount: 120 },
          { name: 'All-Purpose Flour', amount: 300 },
          { name: 'Cream of Tartar', amount: 3 },
          { name: 'Baking Soda', amount: 2 },
          { name: 'Walnuts (chopped)', amount: 113 },
        ],
      },
      {
        group: 'Chocolate Butter Cakes',
        name: "Devil's Food Cake",
        emoji: '😈',
        source: 'Classic American recipe (c. 1900–1920)',
        description: 'A darker, richer chocolate butter cake popularized in the early 1900s. Hot coffee deepens the cocoa flavor and keeps the crumb moist. Traditionally paired with a white or fluffy frosting for dramatic contrast.',
        leaveningNote: 'Uses baking soda (8g) — the acidity of the cocoa activates it. Do not substitute baking powder.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'All-Purpose Flour', amount: 240 },
          { name: 'Cocoa Powder (Natural)', amount: 48 },
          { name: 'Baking Soda', amount: 8 },
          { name: 'Salt', amount: 3 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'Coffee (brewed)', amount: 120 },
        ],
      },
      {
        group: 'Chocolate Butter Cakes',
        name: 'Marble Cake',
        emoji: '🌑',
        source: 'Victorian American recipe (c. late 1800s)',
        description: 'A Victorian showpiece — vanilla and chocolate batters swirled together in the pan. The visual drama is the point. Rich, tender, and nostalgic.',
        leaveningNote: 'Uses 2½ tsp baking powder (10g) in the base vanilla batter. The chocolate swirl uses the same batter with added cocoa — no extra leavening needed.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Granulated Sugar', amount: 350 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Vanilla Extract', amount: 15 },
          { name: 'All-Purpose Flour', amount: 330 },
          { name: 'Baking Powder', amount: 10 },
          { name: 'Salt', amount: 3 },
          { name: 'Whole Milk', amount: 270 },
          { name: 'Cocoa Powder (Natural)', amount: 24 },
        ],
      },
      {
        group: 'Vegetable Butter Cakes',
        name: 'Carrot Cake (Classic)',
        emoji: '🥕',
        source: 'Classic American recipe (c. 1960s–1970s)',
        description: 'Moist, warmly spiced, and loaded with grated carrot and walnuts. Oil-based for exceptional moisture — the definitive mid-century American layer cake. Almost always paired with cream cheese frosting.',
        leaveningNote: 'Uses baking soda (10g) — the carrots and brown sugar provide enough acidity. Some versions add a small amount of baking powder too.',
        ingredients: [
          { name: 'Vegetable Oil', amount: 220 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Whole Egg (large)', amount: 150 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'All-Purpose Flour', amount: 240 },
          { name: 'Baking Soda', amount: 10 },
          { name: 'Cinnamon', amount: 6 },
          { name: 'Nutmeg', amount: 2 },
          { name: 'Salt', amount: 3 },
          { name: 'Carrot (grated)', amount: 200 },
          { name: 'Walnuts (chopped)', amount: 100 },
        ],
      },
      {
        group: 'Fruit Butter Cakes',
        name: 'Banana Cake',
        emoji: '🍌',
        source: 'Classic American recipe (c. 1930s)',
        description: 'Banana cakes became popular in the 1930s as bananas arrived widely in American markets. Creamed butter, ripe mashed bananas, and buttermilk make an exceptionally tender crumb.',
        leaveningNote: 'Uses baking soda (8g) activated by the buttermilk. The riper the bananas, the better — very ripe bananas add natural sweetness and more moisture.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'Banana (mashed)', amount: 225 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'All-Purpose Flour', amount: 240 },
          { name: 'Baking Soda', amount: 8 },
          { name: 'Salt', amount: 3 },
          { name: 'Buttermilk', amount: 120 },
        ],
      },
      {
        group: 'Yellow Butter Cakes',
        name: 'Vanilla Birthday Cake',
        emoji: '🎂',
        source: 'Classic American recipe',
        description: 'The standard American celebration cake — pure vanilla, perfectly balanced, designed to hold up under a generous layer of frosting. Reliable, crowd-pleasing, and exactly what a birthday cake should be.',
        leaveningNote: 'Uses 2½ tsp baking powder (10g). The four whole eggs provide both richness and structure.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 170 },
          { name: 'Granulated Sugar', amount: 350 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Vanilla Extract', amount: 15 },
          { name: 'All-Purpose Flour', amount: 300 },
          { name: 'Baking Powder', amount: 10 },
          { name: 'Salt', amount: 3 },
          { name: 'Whole Milk', amount: 240 },
        ],
      },
      {
        group: 'Yellow Butter Cakes',
        name: 'Brown Butter Cake',
        emoji: '🧈',
        source: 'Classic American recipe',
        description: 'Beurre noisette — butter cooked until the milk solids turn golden and nutty — transforms a simple butter cake into something complex and memorable. Richer and more interesting than a standard yellow cake.',
        leaveningNote: 'Uses 2 tsp baking powder (8g). Brown the butter ahead and let it cool to a soft solid before creaming — it must be firm, not liquid.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Whole Egg (large)', amount: 150 },
          { name: 'Vanilla Extract', amount: 15 },
          { name: 'All-Purpose Flour', amount: 300 },
          { name: 'Baking Powder', amount: 8 },
          { name: 'Salt', amount: 3 },
          { name: 'Whole Milk', amount: 240 },
        ],
      },
      {
        group: 'Flavored Butter Cakes',
        name: 'Coconut Butter Cake',
        emoji: '🥥',
        source: 'Classic American recipe',
        description: 'A butter cake made with coconut milk instead of regular milk, with shredded coconut folded into the batter. Delicate coconut flavor throughout — distinct from our coconut layer cake which uses coconut as a topping.',
        leaveningNote: 'Uses 2½ tsp baking powder (10g). Coconut milk is slightly denser than regular milk — do not substitute light coconut milk.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 170 },
          { name: 'Granulated Sugar', amount: 350 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'All-Purpose Flour', amount: 300 },
          { name: 'Baking Powder', amount: 10 },
          { name: 'Salt', amount: 3 },
          { name: 'Coconut Milk (canned)', amount: 180 },
          { name: 'Shredded Coconut', amount: 40 },
        ],
      },
    ],
  },

  {
    id: 'foam',
    name: 'Foam / Sponge Cake',
    emoji: '🌬️',
    category: 'Classic',
    description: 'Leavened entirely by whipped eggs — no butter, no chemical leavening. Light, airy, and elegant.',
    characteristics: ['Very light', 'Airy', 'Egg-forward'],
    examples: ['Sponge Cake', 'Lady Cake', 'Savory Cake', 'Fancy Cake'],
    scienceNote: 'Whipped eggs trap air which expands in the oven. No fat means the gluten network can stretch unimpeded, giving maximum lift.',
    color: 'from-sky-300 to-blue-400',
    baseFormula: [
      { name: 'Granulated Sugar', amount: 400 },
      { name: 'Whole Egg (large)', amount: 350 },
      { name: 'All-Purpose Flour', amount: 300 },
    ],
    recipes: [
      {
        group: 'Sponge Cakes',
        name: 'Sponge Cake No. 1 (Classic)',
        emoji: '☁️',
        source: 'New York Cake Book, 1904',
        description: 'The quintessential American sponge cake — beaten yolks, whipped whites, and a whisper of lemon. Light as air.',
        leaveningNote: 'No chemical leavening — fully reliant on beaten eggs. This is correct and intentional for sponge cake.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 4, note: 'Not in original — common modern addition' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 400 },
          { name: 'Egg Yolk', amount: 140 },
          { name: 'Egg White', amount: 210 },
          { name: 'All-Purpose Flour', amount: 180 },
          { name: 'Lemon Zest', amount: 5 },
          { name: 'Lemon Juice', amount: 15 },
        ],
      },
      {
        group: 'Sponge Cakes',
        name: 'Sponge Cake No. 2 (White)',
        emoji: '🤍',
        source: 'New York Cake Book, 1904',
        description: 'A white sponge cake using only egg whites — forerunner of the modern angel food cake. Light, delicate, and clean.',
        leaveningNote: 'Original uses cream of tartar (3g) with whites only — this is the correct method for a white sponge/angel food style cake.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original — adds depth' },
          { name: 'Almond Extract', amount: 2, note: 'Not in original — classic pairing with white cake' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'All-Purpose Flour', amount: 120 },
          { name: 'Egg White', amount: 300 },
          { name: 'Cream of Tartar', amount: 3 },
        ],
      },
      {
        group: 'Lady & Fancy Cakes',
        name: 'Lady Cake',
        emoji: '👒',
        source: 'New York Cake Book, 1904',
        description: 'A refined Victorian party cake using 12 egg whites — perfectly white, very light, flavored with bitter almond or lemon. Frosted with vanilla icing.',
        leaveningNote: 'No leavening — relies entirely on 12 whipped egg whites for lift. This is correct for the style.',
        optionalAdditions: [
          { name: 'Salt', amount: 2, note: 'Not in original — helps stabilize the whites' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 170 },
          { name: 'Egg White', amount: 360 },
          { name: 'All-Purpose Flour', amount: 340 },
          { name: 'Almond Extract', amount: 3 },
          { name: 'Lemon Zest', amount: 5 },
        ],
      },
      {
        group: 'Lady & Fancy Cakes',
        name: 'Fancy Cakes (Small Sponges)',
        emoji: '🫐',
        source: 'New York Cake Book, 1904',
        description: 'Small individual sponge cakes — lemon-flavored, baked in patties, and topped with a sugar plum. The Victorian cupcake.',
        leaveningNote: 'No leavening — egg foam provides all the lift. Bake in small tins or muffin cups.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 227 },
          { name: 'Egg Yolk', amount: 80 },
          { name: 'Egg White', amount: 120 },
          { name: 'All-Purpose Flour', amount: 227 },
          { name: 'Lemon Extract', amount: 5 },
        ],
      },
      {
        group: 'Lady & Fancy Cakes',
        name: 'Savory Cakes (Coriander Sponges)',
        emoji: '🌿',
        source: 'New York Cake Book, 1904',
        description: 'A curious and delicious sponge drop cake flavored with coriander seed and fresh lemon — baked as spoonfuls on a buttered pan and dusted with sugar.',
        leaveningNote: 'No leavening — egg foam only. Drop from a large spoon onto buttered pans.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Whole Egg (large)', amount: 400 },
          { name: 'All-Purpose Flour', amount: 453 },
          { name: 'Lemon Zest', amount: 8 },
          { name: 'Lemon Juice', amount: 15 },
        ],
      },
      {
        group: 'Angel Food',
        name: 'Angel Food Cake',
        emoji: '👼',
        source: 'Classic American recipe',
        description: 'Pure egg white foam baked in an ungreased tube pan — no fat, no yolks, no butter. The lightest cake in existence. Snow-white crumb, slightly chewy, and impossibly airy.',
        leaveningNote: 'No baking powder — 12 beaten egg whites provide all the lift. The pan must be completely grease-free or the foam will not cling and rise.',
        ingredients: [
          { name: 'Cake Flour', amount: 120 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Egg White', amount: 360 },
          { name: 'Cream of Tartar', amount: 3 },
          { name: 'Salt', amount: 1 },
          { name: 'Vanilla Extract', amount: 5 },
        ],
      },
      {
        group: 'European Sponges',
        name: 'Genoise (Classic European Sponge)',
        emoji: '🇫🇷',
        source: 'Classic French/Italian recipe',
        description: 'Whole eggs and sugar whisked warm over a bain-marie until tripled in volume, then folded with flour and a touch of melted butter. The foundation of European pâtisserie — used for layer cakes, roulades, and entremets.',
        leaveningNote: 'No chemical leavening — the warm-beaten eggs provide all the air. The bain-marie is essential; cold eggs will not trap enough foam.',
        ingredients: [
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Granulated Sugar', amount: 150 },
          { name: 'Cake Flour', amount: 120 },
          { name: 'Unsalted Butter', amount: 42 },
          { name: 'Vanilla Extract', amount: 5 },
        ],
      },
      {
        group: 'European Sponges',
        name: 'Joconde / Almond Sponge',
        emoji: '🌰',
        source: 'Classic French recipe',
        description: 'A thin, flexible almond-flour sponge used as the base for entremets and opera cake. Rich with almond flour and eggs, lightened with whipped whites. Baked very thin on a sheet pan at high heat.',
        leaveningNote: 'No chemical leavening — beaten egg whites provide lift. Spread thin (5mm) on a lined sheet pan; it bakes in 7–10 minutes at 425°F.',
        ingredients: [
          { name: 'Almond Flour', amount: 100 },
          { name: 'Powdered Sugar', amount: 120 },
          { name: 'Whole Egg (large)', amount: 150 },
          { name: 'Egg White', amount: 90 },
          { name: 'Granulated Sugar', amount: 25 },
          { name: 'All-Purpose Flour', amount: 30 },
          { name: 'Unsalted Butter', amount: 28 },
        ],
      },
      {
        group: 'European Sponges',
        name: 'Swiss Roll / Roulade',
        emoji: '🌀',
        source: 'Classic European recipe',
        description: 'A thin sponge sheet baked quickly, then rolled while still warm to create a spiral. Filled with jam, cream, or ganache. The technique of rolling while hot is what prevents cracking.',
        leaveningNote: 'No chemical leavening — beaten whole eggs provide lift. Do not overbake: the sheet must be pliable enough to roll without cracking.',
        ingredients: [
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Granulated Sugar', amount: 150 },
          { name: 'All-Purpose Flour', amount: 90 },
          { name: 'Vanilla Extract', amount: 5 },
        ],
      },
    ],
  },

  {
    id: 'chiffon',
    name: 'Chiffon Cake',
    emoji: '🌀',
    category: 'Classic',
    description: 'A lighter variant of sponge cake — uses oil for moisture and whipped egg whites for lift. Invented in the 1920s.',
    characteristics: ['Moist', 'Light', 'Tender crumb'],
    examples: ['Classic Chiffon', 'Lemon Chiffon', 'Orange Chiffon'],
    scienceNote: 'Oil provides moisture without weighing down the foam. The neutral fat lets the egg foam work unimpeded.',
    color: 'from-orange-300 to-yellow-400',
    baseFormula: [
      { name: 'Cake Flour', amount: 200 },
      { name: 'Granulated Sugar', amount: 200 },
      { name: 'Vegetable Oil', amount: 120 },
      { name: 'Egg Yolk', amount: 80 },
      { name: 'Egg White', amount: 200 },
      { name: 'Whole Milk', amount: 120 },
      { name: 'Baking Powder', amount: 8 },
      { name: 'Cream of Tartar', amount: 3 },
      { name: 'Salt', amount: 3 },
    ],
    recipes: [
      {
        group: 'Classic Chiffon',
        name: 'Original-Style Chiffon Cake',
        emoji: '🌀',
        source: 'Classic American recipe (post-1927)',
        description: 'The definitive chiffon cake — cake flour, vegetable oil, and 7 egg yolks in the batter, with a stiff meringue folded in for lift. Baked in an ungreased tube pan and inverted to cool.',
        leaveningNote: 'Uses 3 tsp baking powder (12g) in the batter plus cream of tartar (2g) in the meringue — both are essential. Do not substitute.',
        ingredients: [
          { name: 'Cake Flour', amount: 240 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Baking Powder', amount: 12 },
          { name: 'Salt', amount: 6 },
          { name: 'Vegetable Oil', amount: 110 },
          { name: 'Egg Yolk', amount: 140 },
          { name: 'Vanilla Extract', amount: 10 },
          { name: 'Egg White', amount: 210 },
          { name: 'Cream of Tartar', amount: 2 },
        ],
      },
      {
        group: 'Classic Chiffon',
        name: 'Cornstarch Cake (Proto-Chiffon)',
        emoji: '🌽',
        source: 'New York Cake Book, 1904',
        description: 'A Victorian "light cake" using cornstarch alongside flour — produces an unusually tender, fine crumb that anticipates the chiffon style.',
        leaveningNote: 'Original uses cream of tartar (6g) + baking soda (5g) — equivalent to about 2 tsp baking powder (8g).',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original — greatly improves the flavor' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 400 },
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'Egg Yolk', amount: 150 },
          { name: 'Egg White', amount: 150 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'All-Purpose Flour', amount: 240 },
          { name: 'Cornstarch', amount: 120 },
          { name: 'Cream of Tartar', amount: 6 },
        ],
      },
      {
        group: 'Flavored Chiffon',
        name: 'Lemon Chiffon Cake',
        emoji: '🍋',
        source: 'Classic American recipe',
        description: 'The chiffon cake formula with fresh lemon juice replacing the water — bright, citrusy, and lighter than air. The lemon flavor permeates every crumb.',
        leaveningNote: 'Uses 3 tsp baking powder (12g) plus cream of tartar (2g) in the meringue. Lemon juice is slightly acidic — the baking powder compensates.',
        ingredients: [
          { name: 'Cake Flour', amount: 240 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Baking Powder', amount: 12 },
          { name: 'Salt', amount: 6 },
          { name: 'Vegetable Oil', amount: 110 },
          { name: 'Egg Yolk', amount: 140 },
          { name: 'Lemon Juice', amount: 180 },
          { name: 'Lemon Zest', amount: 8 },
          { name: 'Egg White', amount: 210 },
          { name: 'Cream of Tartar', amount: 2 },
        ],
      },
      {
        group: 'Flavored Chiffon',
        name: 'Orange Chiffon Cake',
        emoji: '🍊',
        source: 'Classic American recipe',
        description: 'Fresh orange juice and zest replace the water in the classic chiffon formula. Warm, fragrant, and sunny — the orange aroma perfumes the whole kitchen while it bakes.',
        leaveningNote: 'Identical leavening to the classic chiffon. Orange juice is slightly acidic but the effect is minor — keep the full baking powder amount.',
        ingredients: [
          { name: 'Cake Flour', amount: 240 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Baking Powder', amount: 12 },
          { name: 'Salt', amount: 6 },
          { name: 'Vegetable Oil', amount: 110 },
          { name: 'Egg Yolk', amount: 140 },
          { name: 'Orange Juice', amount: 180 },
          { name: 'Orange Zest', amount: 5 },
          { name: 'Egg White', amount: 210 },
          { name: 'Cream of Tartar', amount: 2 },
        ],
      },
      {
        group: 'Flavored Chiffon',
        name: 'Chocolate Chiffon Cake',
        emoji: '🍫',
        source: 'Classic American recipe',
        description: 'Cocoa powder and hot coffee added to the chiffon base — the coffee deepens the chocolate flavor without adding a coffee taste. Rich, airy, and deeply chocolatey.',
        leaveningNote: 'Natural cocoa is acidic — reduce baking powder slightly to 10g and add a small pinch of baking soda to compensate. Hot coffee blooms the cocoa.',
        ingredients: [
          { name: 'Cake Flour', amount: 180 },
          { name: 'Cocoa Powder (Natural)', amount: 48 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Baking Powder', amount: 10 },
          { name: 'Baking Soda', amount: 3 },
          { name: 'Salt', amount: 6 },
          { name: 'Vegetable Oil', amount: 110 },
          { name: 'Egg Yolk', amount: 140 },
          { name: 'Coffee (brewed)', amount: 180 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Egg White', amount: 210 },
          { name: 'Cream of Tartar', amount: 2 },
        ],
      },
    ],
  },

  {
    id: 'oil',
    name: 'Oil Cake',
    emoji: '🫙',
    category: 'Classic',
    description: 'Uses liquid fat instead of creamed butter — stays moist for days and develops flavor as it sits.',
    characteristics: ['Very moist', 'Dense', 'Keeps well'],
    examples: ['Huckleberry Cake', 'Coffee Cake', 'Loaf Cake'],
    scienceNote: 'Liquid fat coats flour proteins more evenly than solid fat, resulting in a very tender crumb that stays moist longer.',
    color: 'from-amber-400 to-orange-500',
    baseFormula: [
      { name: 'All-Purpose Flour', amount: 250 },
      { name: 'Granulated Sugar', amount: 200 },
      { name: 'Vegetable Oil', amount: 120 },
      { name: 'Whole Egg (large)', amount: 100 },
      { name: 'Whole Milk', amount: 120 },
      { name: 'Baking Powder', amount: 8 },
    ],
    recipes: [
      {
        group: 'Fruit & Spice Cakes',
        name: 'Huckleberry Cake',
        emoji: '🫐',
        source: 'New York Cake Book, 1904',
        description: 'A deeply American cake — spiced with allspice, cinnamon, and cloves, loaded with fresh huckleberries. The original blueberry cake.',
        leaveningNote: 'Original uses cream of tartar (5g) + baking soda (5g) — equivalent to about 2 tsp baking powder (8g).',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 4, note: 'Not in original' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 200 },
          { name: 'Molasses', amount: 200 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Cream of Tartar', amount: 5 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'All-Purpose Flour', amount: 360 },
          { name: 'Fresh Blueberries', amount: 240 },
          { name: 'Allspice', amount: 3 },
          { name: 'Cinnamon', amount: 3 },
          { name: 'Cloves', amount: 2 },
        ],
      },
      {
        group: 'Fruit & Spice Cakes',
        name: 'Mountain Cake',
        emoji: '⛰️',
        source: 'New York Cake Book, 1904',
        description: 'A hearty, vanilla-flavored layer cake with a currant jelly topping made from the remaining egg whites. Rustic and satisfying.',
        leaveningNote: 'Original uses cream of tartar (6g) + baking soda (5g) — equivalent to about 2 tsp baking powder (8g).',
        optionalAdditions: [
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 340 },
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'All-Purpose Flour', amount: 453 },
          { name: 'Egg Yolk', amount: 120 },
          { name: 'Egg White', amount: 120 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'Cream of Tartar', amount: 6 },
          { name: 'Vanilla Extract', amount: 5 },
        ],
      },
      {
        group: 'Vegetable Oil Cakes',
        name: 'Zucchini Cake',
        emoji: '🥒',
        source: 'Classic American recipe',
        description: 'Grated zucchini melts into the batter as it bakes, leaving behind extraordinary moisture with no vegetable flavor. Warmly spiced with cinnamon. Often confused for spice cake — the secret ingredient is invisible.',
        leaveningNote: 'Uses baking soda (5g) — the zucchini provides enough natural moisture and slight acidity. A touch of baking powder can be added for extra lift.',
        ingredients: [
          { name: 'Vegetable Oil', amount: 220 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Whole Egg (large)', amount: 150 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'All-Purpose Flour', amount: 240 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'Cinnamon', amount: 5 },
          { name: 'Salt', amount: 3 },
          { name: 'Zucchini (grated)', amount: 240 },
        ],
      },
      {
        group: 'Fruit Oil Cakes',
        name: 'Applesauce Cake',
        emoji: '🍎',
        source: 'Classic American recipe',
        description: 'Applesauce replaces most of the fat and adds natural sweetness and moisture. Warmly spiced with cinnamon and cloves — a Depression-era classic that stays moist for days.',
        leaveningNote: 'Uses baking soda (5g) activated by the acidity of the applesauce. Unsweetened applesauce is preferred — sweetened will make the cake too sweet.',
        ingredients: [
          { name: 'Vegetable Oil', amount: 110 },
          { name: 'Granulated Sugar', amount: 200 },
          { name: 'Applesauce', amount: 245 },
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'All-Purpose Flour', amount: 240 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'Cinnamon', amount: 5 },
          { name: 'Cloves', amount: 2 },
          { name: 'Salt', amount: 3 },
        ],
      },
      {
        group: 'Olive Oil Cakes',
        name: 'Italian Olive Oil Cake',
        emoji: '🫒',
        source: 'Classic Italian recipe',
        description: 'A simple, elegant Italian cake — olive oil gives a fruity, slightly savory depth that butter cannot. Lemon zest brightens everything. Barely sweet, dense, and keeps exceptionally well.',
        leaveningNote: 'Uses baking powder (4g) — just enough for a gentle rise. This cake is meant to be dense and moist, not tall and fluffy.',
        ingredients: [
          { name: 'Olive Oil', amount: 165 },
          { name: 'Granulated Sugar', amount: 250 },
          { name: 'Whole Egg (large)', amount: 150 },
          { name: 'Lemon Zest', amount: 5 },
          { name: 'All-Purpose Flour', amount: 210 },
          { name: 'Baking Powder', amount: 4 },
          { name: 'Salt', amount: 3 },
          { name: 'Whole Milk', amount: 120 },
        ],
      },
      {
        group: 'Fruit Oil Cakes',
        name: 'Pineapple Upside-Down Cake',
        emoji: '🍍',
        source: 'Classic American recipe (c. 1920s)',
        description: 'Brown sugar and butter caramelize on the bottom of the pan with pineapple rings, then a simple butter cake is poured over the top. Inverted when hot to reveal the glossy, caramelized fruit topping.',
        leaveningNote: 'Uses baking powder (4g) in the cake layer. The topping is not baked separately — it caramelizes under the cake as it bakes.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 170 },
          { name: 'Brown Sugar (Light)', amount: 300 },
          { name: 'Pineapple (canned rings)', amount: 240 },
          { name: 'Granulated Sugar', amount: 200 },
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'All-Purpose Flour', amount: 180 },
          { name: 'Baking Powder', amount: 4 },
          { name: 'Salt', amount: 3 },
          { name: 'Whole Milk', amount: 120 },
          { name: 'Vanilla Extract', amount: 5 },
        ],
      },
    ],
  },

  {
    id: 'flourless',
    name: 'Flourless Cake',
    emoji: '🍫',
    category: 'Modern',
    description: 'No flour — relies on chocolate, almond flour, or eggs for structure. Dense, fudgy, and intensely flavored.',
    characteristics: ['Dense', 'Fudgy', 'Gluten-free'],
    examples: ['Flourless Chocolate', 'Almond Torte'],
    scienceNote: 'Without gluten, structure comes entirely from egg proteins and the binding properties of chocolate or nut flours.',
    color: 'from-stone-600 to-gray-800',
    baseFormula: [
      { name: 'Dark Chocolate Bar', amount: 200 },
      { name: 'Unsalted Butter', amount: 115 },
      { name: 'Granulated Sugar', amount: 150 },
      { name: 'Whole Egg (large)', amount: 200 },
      { name: 'Cocoa Powder (Natural)', amount: 30 },
    ],
    recipes: [
      {
        group: 'Flourless Chocolate',
        name: 'Traditional Flourless Chocolate Cake',
        emoji: '🍫',
        source: 'Classic American recipe',
        description: 'Dark chocolate and butter melted together, enriched with egg yolks and almond flour, then lightened with stiffly beaten egg whites. Dense, fudgy, and intensely chocolatey.',
        leaveningNote: 'No baking powder or soda — the beaten egg whites provide all the lift. Do not overbake; the center should still have a slight wobble when it comes out.',
        ingredients: [
          { name: 'Dark Chocolate Bar', amount: 227 },
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Granulated Sugar', amount: 150 },
          { name: 'Egg Yolk', amount: 80 },
          { name: 'Egg White', amount: 120 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Salt', amount: 2 },
          { name: 'Almond Flour', amount: 75 },
        ],
      },
      {
        group: 'Almond Cakes',
        name: 'Almond Macaroon Cake',
        emoji: '🌸',
        source: 'New York Cake Book, 1904',
        description: 'A flourless ground almond cake made with rose water and egg whites — the Victorian almond torte. Chewy, fragrant, and very rich.',
        leaveningNote: 'No leavening — egg whites and ground almonds provide structure. This is intentionally dense.',
        optionalAdditions: [
          { name: 'Almond Extract', amount: 2, note: 'Not in original — enhances almond flavor' },
          { name: 'Vanilla Extract', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Almonds (sliced)', amount: 227 },
          { name: 'Rose Water', amount: 15 },
          { name: 'Egg White', amount: 90 },
          { name: 'Granulated Sugar', amount: 227 },
        ],
      },
      {
        group: 'Almond Cakes',
        name: 'Coconut Macaroon Cake',
        emoji: '🥥',
        source: 'New York Cake Book, 1904',
        description: 'Ground coconut bound with egg whites and sugar — no flour, no fat. Baked as a large cake or dropped as small macaroon rounds.',
        leaveningNote: 'No leavening — egg whites provide all the structure.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 4, note: 'Not in original' },
          { name: 'Almond Extract', amount: 2, note: 'Not in original — classic pairing with coconut' },
        ],
        ingredients: [
          { name: 'Shredded Coconut', amount: 227 },
          { name: 'Granulated Sugar', amount: 227 },
          { name: 'Egg White', amount: 180 },
          { name: 'Lemon Juice', amount: 10 },
        ],
      },
      {
        group: 'Almond Tortes',
        name: 'Flourless Almond Torte',
        emoji: '🌰',
        source: 'Classic European recipe',
        description: 'Ground almonds, butter, sugar, and eggs — no flour at all. Dense, moist, and intensely nutty. A European torte in the purest sense. Keeps well for several days and actually improves overnight.',
        leaveningNote: 'No leavening — the eggs provide all the structure. The torte will be flat and dense; this is correct and intentional.',
        ingredients: [
          { name: 'Almond Flour', amount: 200 },
          { name: 'Granulated Sugar', amount: 150 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Salt', amount: 2 },
        ],
      },
      {
        group: 'Flourless Chocolate',
        name: 'Chocolate Lava Cake',
        emoji: '🌋',
        source: 'Classic French recipe (c. 1980s)',
        description: 'Individual flourless chocolate cakes baked just long enough to set the exterior while the center stays molten. Served immediately. Dramatically underbaked by design — the runny center is the entire point.',
        leaveningNote: 'No leavening — a tiny amount of flour (30g) provides minimal structure. The key is precise timing: 12 minutes at 425°F in a preheated ramekin.',
        ingredients: [
          { name: 'Dark Chocolate Bar', amount: 170 },
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Granulated Sugar', amount: 100 },
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'Egg Yolk', amount: 40 },
          { name: 'All-Purpose Flour', amount: 30 },
          { name: 'Vanilla Extract', amount: 3 },
          { name: 'Salt', amount: 1 },
        ],
      },
      {
        group: 'Meringue Cakes',
        name: 'Pavlova',
        emoji: '🦢',
        source: 'Classic Australian/New Zealand recipe (c. 1920s)',
        description: 'A large meringue baked low and slow until the outside is crisp and the inside remains marshmallow-soft. Named after the ballerina Anna Pavlova. Topped with whipped cream and fresh fruit.',
        leaveningNote: 'No leavening — beaten egg whites provide all the structure. Vinegar and cornstarch are essential: they create the soft, marshmallow interior.',
        ingredients: [
          { name: 'Egg White', amount: 120 },
          { name: 'Granulated Sugar', amount: 200 },
          { name: 'Cornstarch', amount: 8 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'White Vinegar', amount: 5 },
        ],
      },
    ],
  },

  {
    id: 'cheesecake',
    name: 'Cheesecake',
    emoji: '🧀',
    category: 'Classic',
    description: 'A dense, custard-like cake built on cream cheese or fresh cheese. Rich, tangy, and creamy.',
    characteristics: ['Dense', 'Creamy', 'Tangy'],
    examples: ['Classic Cheesecake', 'New York Style'],
    scienceNote: 'The high fat and protein content of cream cheese sets into a smooth, dense texture when baked gently.',
    color: 'from-yellow-100 to-amber-200',
    baseFormula: [
      { name: 'Cream Cheese', amount: 450 },
      { name: 'Granulated Sugar', amount: 150 },
      { name: 'Whole Egg (large)', amount: 150 },
      { name: 'Sour Cream', amount: 120 },
      { name: 'Vanilla Extract', amount: 5 },
    ],
    recipes: [
      {
        group: 'Classic Cheesecakes',
        name: 'Early New York Cheesecake',
        emoji: '🗽',
        source: 'Classic American recipe',
        description: 'The definitive New York cheesecake — two pounds of cream cheese, four eggs, and heavy cream on a graham cracker crust. Baked at 325°F and cooled slowly in the oven to prevent cracking.',
        leaveningNote: 'No baking powder or soda. The eggs set the filling as a custard. Slow oven cooling is critical — do not rush it.',
        ingredients: [
          { name: 'Cream Cheese', amount: 907 },
          { name: 'Granulated Sugar', amount: 200 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Heavy Cream', amount: 240 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Lemon Juice', amount: 15 },
        ],
      },
      {
        group: 'Classic Cheesecakes',
        name: 'Cream Cake No. 1 (Victorian)',
        emoji: '🫙',
        source: 'New York Cake Book, 1904',
        description: 'A Victorian "cream cake" made with sweet cream and raisins — a rich, dense cake built on cream as the primary dairy. The 1904 ancestor of the cheesecake tradition.',
        leaveningNote: 'No leavening — egg foam and cream provide all the lift.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original — highly recommended' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Granulated Sugar', amount: 340 },
          { name: 'Whole Egg (large)', amount: 350 },
          { name: 'Nutmeg', amount: 3 },
          { name: 'All-Purpose Flour', amount: 680 },
          { name: 'Heavy Cream', amount: 240 },
          { name: 'Raisins', amount: 200 },
        ],
      },
      {
        group: 'No-Bake Cheesecakes',
        name: 'No-Bake Cheesecake',
        emoji: '❄️',
        source: 'Classic American recipe',
        description: 'Cream cheese whipped with powdered sugar and set with gelatin — no oven required. Light, mousse-like texture compared to baked cheesecake. Chills for 4 hours minimum.',
        leaveningNote: 'No baking — gelatin sets the filling. Blooming the gelatin properly (in cold water first) is critical for a smooth, even set.',
        ingredients: [
          { name: 'Cream Cheese', amount: 454 },
          { name: 'Powdered Sugar', amount: 120 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Heavy Cream', amount: 240 },
          { name: 'Gelatin (unflavored)', amount: 7 },
          { name: 'Lemon Juice', amount: 15 },
        ],
      },
      {
        group: 'International Cheesecakes',
        name: 'Japanese Cheesecake (Soufflé Style)',
        emoji: '🗼',
        source: 'Classic Japanese recipe',
        description: 'A light, cloud-like cheesecake that merges cream cheese custard with a meringue — far less dense than New York style. Jiggles when shaken. Baked in a water bath at a gentle temperature.',
        leaveningNote: 'No chemical leavening — stiffly beaten egg whites provide all the lift. The water bath is non-negotiable; without it the custard curdles.',
        ingredients: [
          { name: 'Cream Cheese', amount: 227 },
          { name: 'Egg Yolk', amount: 80 },
          { name: 'Egg White', amount: 120 },
          { name: 'Granulated Sugar', amount: 100 },
          { name: 'Whole Milk', amount: 120 },
          { name: 'All-Purpose Flour', amount: 30 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Lemon Juice', amount: 10 },
        ],
      },
      {
        group: 'International Cheesecakes',
        name: 'Ricotta Cheesecake (Italian Style)',
        emoji: '🇮🇹',
        source: 'Classic Italian recipe',
        description: 'Whole-milk ricotta, eggs, and a little flour — drier, lighter, and less rich than cream cheese cheesecake. Lemon zest is essential. The Italian ancestor of the American cheesecake.',
        leaveningNote: 'No chemical leavening — eggs set the filling. Drain the ricotta well overnight if it seems watery, or the cake will not set properly.',
        ingredients: [
          { name: 'Ricotta Cheese', amount: 907 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Granulated Sugar', amount: 150 },
          { name: 'Lemon Zest', amount: 8 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'All-Purpose Flour', amount: 60 },
          { name: 'Salt', amount: 2 },
        ],
      },
    ],
  },

  {
    id: 'icecream',
    name: 'Ice Cream Cake',
    emoji: '🍨',
    category: 'Modern',
    description: 'Cake layers with ice cream — baked thin, cooled, then assembled with frozen filling.',
    characteristics: ['Frozen', 'Layered', 'Celebratory'],
    examples: ['Jelly Layer Cake', 'Ice Cream Layer Cake'],
    scienceNote: 'Thin cake layers provide texture and structure around frozen ice cream.',
    color: 'from-pink-300 to-purple-400',
    baseFormula: [
      { name: 'All-Purpose Flour', amount: 200 },
      { name: 'Granulated Sugar', amount: 180 },
      { name: 'Unsalted Butter', amount: 100 },
      { name: 'Whole Egg (large)', amount: 150 },
      { name: 'Whole Milk', amount: 100 },
      { name: 'Baking Powder', amount: 6 },
    ],
    recipes: [
      {
        group: 'Jelly Layer Cakes',
        name: 'Jelly Cake No. 1',
        emoji: '🍓',
        source: 'New York Cake Book, 1904',
        description: 'Thin layers baked in jelly-cake tins, stacked with fruit jelly between each layer. The Victorian layer cake — a classic American party cake.',
        leaveningNote: 'Original uses cream of tartar (3g) + baking soda (2g) — equivalent to 1 tsp baking powder (4g).',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original — recommended' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'Whole Egg (large)', amount: 300 },
          { name: 'Cream of Tartar', amount: 3 },
          { name: 'Baking Soda', amount: 2 },
          { name: 'All-Purpose Flour', amount: 453 },
        ],
      },
      {
        group: 'Jelly Layer Cakes',
        name: 'Jelly Cake No. 2 (Lemon)',
        emoji: '🍋',
        source: 'New York Cake Book, 1904',
        description: 'A fine lemon layer cake with richer egg content — 8 eggs give a golden, tender crumb. Filled with jelly or lemon curd between layers.',
        leaveningNote: 'No leavening — 8 whole eggs provide the lift. This is intentional for the style.',
        optionalAdditions: [
          { name: 'Baking Powder', amount: 4, note: 'Not in original — add for a lighter crumb' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 227 },
          { name: 'Unsalted Butter', amount: 170 },
          { name: 'Whole Egg (large)', amount: 400 },
          { name: 'All-Purpose Flour', amount: 453 },
          { name: 'Lemon Juice', amount: 20 },
          { name: 'Lemon Zest', amount: 8 },
        ],
      },
    ],
  },

  {
    id: 'layer',
    name: 'Layer Cake',
    emoji: '🎂',
    category: 'Classic',
    description: 'Multiple thin layers stacked with fillings — the American celebration cake.',
    characteristics: ['Tall', 'Layered', 'Festive'],
    examples: ['Chocolate Layer Cake', 'Coconut Layer Cake', 'Lemon Currant Cake'],
    scienceNote: 'Thin layers baked separately then assembled create more surface area for filling and a better filling-to-cake ratio.',
    color: 'from-rose-400 to-pink-500',
    baseFormula: [
      { name: 'All-Purpose Flour', amount: 280 },
      { name: 'Granulated Sugar', amount: 240 },
      { name: 'Unsalted Butter', amount: 130 },
      { name: 'Whole Egg (large)', amount: 200 },
      { name: 'Whole Milk', amount: 160 },
      { name: 'Baking Powder', amount: 9 },
    ],
    recipes: [
      {
        group: 'Chocolate Layer Cakes',
        name: 'Chocolate Layer Cake',
        emoji: '🍫',
        source: 'New York Cake Book, 1904',
        description: 'An 1904 New York chocolate layer cake — baked in thin jelly-cake tins and filled with a chocolate-vanilla icing between layers. The original chocolate layer cake.',
        leaveningNote: 'Original uses cream of tartar (3g) + baking soda (2g) — equivalent to 1 tsp baking powder (4g).',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original — add to batter as well as filling' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'All-Purpose Flour', amount: 420 },
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Granulated Sugar', amount: 400 },
          { name: 'Egg Yolk', amount: 150 },
          { name: 'Egg White', amount: 90 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'Cream of Tartar', amount: 3 },
          { name: 'Baking Soda', amount: 2 },
          { name: 'Dutch Cocoa Powder', amount: 40 },
        ],
      },
      {
        group: 'Coconut Layer Cakes',
        name: 'Coconut Layer Cake No. 1',
        emoji: '🥥',
        source: 'New York Cake Book, 1904',
        description: 'A large, impressive coconut layer cake — three cups of grated coconut in the batter, with a sweetened coconut filling between layers.',
        leaveningNote: 'Original uses cream of tartar (6g) + baking soda (5g) — equivalent to about 2 tsp baking powder (8g).',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'All-Purpose Flour', amount: 480 },
          { name: 'Granulated Sugar', amount: 600 },
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Cream of Tartar', amount: 6 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'Shredded Coconut', amount: 360 },
          { name: 'Egg White', amount: 90 },
          { name: 'Lemon Zest', amount: 5 },
          { name: 'Whole Milk', amount: 120 },
        ],
      },
      {
        group: 'Coconut Layer Cakes',
        name: 'Coconut Sponge Layer Cake',
        emoji: '🌴',
        source: 'New York Cake Book, 1904',
        description: 'A coconut-lemon sponge cake — egg-based and light, with a full grated coconut folded in at the end. Delicate and fragrant.',
        leaveningNote: 'No chemical leavening — egg foam provides lift, which is correct for this sponge-style cake.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 4, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 480 },
          { name: 'Egg Yolk', amount: 180 },
          { name: 'Egg White', amount: 180 },
          { name: 'Shredded Coconut', amount: 320 },
          { name: 'All-Purpose Flour', amount: 60 },
          { name: 'Lemon Juice', amount: 15 },
          { name: 'Salt', amount: 2 },
        ],
      },
      {
        group: 'Fruit Layer Cakes',
        name: 'Lemon Currant Cake',
        emoji: '🍋',
        source: 'New York Cake Book, 1904',
        description: 'A rich lemon cake with currants and lemon peel cut in strips — bright, buttery, and deeply fruity.',
        leaveningNote: 'No leavening — 7 eggs provide all the rise. This is the correct approach for this rich butter cake.',
        optionalAdditions: [
          { name: 'Baking Powder', amount: 4, note: 'Not in original — add for a slightly lighter texture' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 340 },
          { name: 'Egg Yolk', amount: 140 },
          { name: 'Egg White', amount: 210 },
          { name: 'All-Purpose Flour', amount: 453 },
          { name: 'Lemon Juice', amount: 20 },
          { name: 'Lemon Zest', amount: 10 },
          { name: 'Dried Currants', amount: 150 },
        ],
      },
      {
        group: 'American Layer Cakes',
        name: 'Red Velvet Cake',
        emoji: '❤️',
        source: 'Classic Southern American recipe (c. 1920s–1940s)',
        description: 'A subtly chocolatey, deeply red buttermilk layer cake with a distinctive tangy crumb. Traditionally paired exclusively with cream cheese frosting. The red color originally came from a reaction between cocoa and buttermilk.',
        leaveningNote: 'Uses baking soda (8g) activated by the buttermilk. The cocoa is natural (not Dutch), which is essential for the original color reaction.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Cocoa Powder (Natural)', amount: 12 },
          { name: 'Red Food Coloring', amount: 15 },
          { name: 'Buttermilk', amount: 240 },
          { name: 'All-Purpose Flour', amount: 300 },
          { name: 'Baking Soda', amount: 8 },
          { name: 'Salt', amount: 3 },
          { name: 'White Vinegar', amount: 5 },
        ],
      },
      {
        group: 'American Layer Cakes',
        name: 'Hummingbird Cake',
        emoji: '🌺',
        source: 'Classic Southern American recipe (c. 1970s)',
        description: 'A beloved Southern layer cake loaded with mashed banana, crushed pineapple, and toasted pecans. Oil-based for extraordinary moisture. Almost always finished with cream cheese frosting.',
        leaveningNote: 'Uses baking soda (5g) — the fruit acids from banana and pineapple activate it. Do not substitute baking powder.',
        ingredients: [
          { name: 'Vegetable Oil', amount: 220 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Whole Egg (large)', amount: 150 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Banana (mashed)', amount: 225 },
          { name: 'Pineapple (canned rings)', amount: 200 },
          { name: 'All-Purpose Flour', amount: 240 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'Cinnamon', amount: 5 },
          { name: 'Salt', amount: 3 },
          { name: 'Walnuts (chopped)', amount: 100 },
        ],
      },
      {
        group: 'American Layer Cakes',
        name: 'Italian Cream Cake',
        emoji: '🌿',
        source: 'Classic American recipe (Southern style)',
        description: 'A rich Southern layer cake with butter, oil, buttermilk, shredded coconut, and pecans. Despite the name it is American, not Italian. Always finished with cream cheese frosting and toasted coconut.',
        leaveningNote: 'Uses baking soda (5g) activated by the buttermilk. The combination of butter and oil gives both flavor and long-lasting moisture.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Vegetable Oil', amount: 110 },
          { name: 'Granulated Sugar', amount: 400 },
          { name: 'Egg Yolk', amount: 125 },
          { name: 'Egg White', amount: 150 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Buttermilk', amount: 240 },
          { name: 'All-Purpose Flour', amount: 240 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'Salt', amount: 3 },
          { name: 'Shredded Coconut', amount: 80 },
          { name: 'Walnuts (chopped)', amount: 100 },
        ],
      },
      {
        group: 'Classic American Layer Cakes',
        name: 'Boston Cream Pie',
        emoji: '🍮',
        source: 'Classic American recipe (c. 1856, Parker House Hotel)',
        description: 'Two layers of yellow butter cake filled with vanilla pastry cream and topped with chocolate ganache. Technically a cake, historically called a pie — one of the great American desserts.',
        leaveningNote: 'Uses 2 tsp baking powder (8g) in the cake layers. The pastry cream filling is cooked separately on the stovetop and must be chilled before assembly.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Granulated Sugar', amount: 200 },
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'Vanilla Extract', amount: 10 },
          { name: 'All-Purpose Flour', amount: 180 },
          { name: 'Baking Powder', amount: 8 },
          { name: 'Salt', amount: 3 },
          { name: 'Whole Milk', amount: 120 },
          { name: 'Heavy Cream', amount: 120 },
          { name: 'Dark Chocolate Bar', amount: 100 },
        ],
      },
      {
        group: 'European Layer Cakes',
        name: 'Black Forest Cake',
        emoji: '🍒',
        source: 'Classic German recipe (Schwarzwälder Kirschtorte)',
        description: 'Layers of chocolate sponge, whipped cream, and sour cherries soaked in Kirsch. A German classic — bold, dramatic, and festive. The Kirsch (cherry brandy) is traditional and non-negotiable in the original.',
        leaveningNote: 'Uses baking powder (8g) and baking soda (3g) together — the Dutch cocoa is alkaline so baking soda helps balance. The sponge layers should be thin.',
        ingredients: [
          { name: 'All-Purpose Flour', amount: 200 },
          { name: 'Dutch Cocoa Powder', amount: 48 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Baking Powder', amount: 8 },
          { name: 'Baking Soda', amount: 3 },
          { name: 'Salt', amount: 3 },
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Buttermilk', amount: 240 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Fresh Cherries', amount: 300 },
          { name: 'Heavy Cream', amount: 360 },
        ],
      },
    ],
  },

  {
    id: 'specialty',
    name: 'Specialty Cake',
    emoji: '✨',
    category: 'Classic',
    description: 'Unique cakes with distinctive methods — spice cakes, fruit cakes, gingerbread, and molasses-based cakes.',
    characteristics: ['Unique method', 'Bold flavors', 'Keeps well'],
    examples: ['Fruit Cake', 'Coffee Cake', 'Gingerbread', 'Spice Cake', 'Loaf Cake'],
    scienceNote: 'Molasses and brown sugar add both flavor and moisture-retention. Spices were historically used to mask the flavor of aging fruit and butter.',
    color: 'from-amber-600 to-brown-700',
    baseFormula: [
      { name: 'All-Purpose Flour', amount: 300 },
      { name: 'Brown Sugar (Dark)', amount: 200 },
      { name: 'Molasses', amount: 80 },
      { name: 'Unsalted Butter', amount: 115 },
      { name: 'Whole Egg (large)', amount: 100 },
      { name: 'Baking Soda', amount: 5 },
      { name: 'Cinnamon', amount: 5 },
      { name: 'Ginger (ground)', amount: 5 },
    ],
    recipes: [
      {
        group: 'Fruit Cakes',
        name: 'Classic Fruit Cake',
        emoji: '🍒',
        source: 'New York Cake Book, 1904',
        description: 'A Victorian fruit cake — currants, raisins, citron peel, and warm spices in a rich butter batter. Made for Christmas and special occasions.',
        leaveningNote: 'No leavening — very dense by design. This is correct for a traditional fruit cake.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original' },
          { name: 'Salt', amount: 4, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 340 },
          { name: 'Egg Yolk', amount: 140 },
          { name: 'Egg White', amount: 210 },
          { name: 'All-Purpose Flour', amount: 453 },
          { name: 'Candied Citron Peel', amount: 113 },
          { name: 'Cinnamon', amount: 5 },
          { name: 'Nutmeg', amount: 3 },
          { name: 'Dried Currants', amount: 227 },
          { name: 'Raisins', amount: 227 },
        ],
      },
      {
        group: 'Fruit Cakes',
        name: 'Rich Loaf Cake',
        emoji: '🎄',
        source: 'New York Cake Book, 1904',
        description: 'A Victorian molasses and sour milk loaf cake — a monumental recipe with two pounds of currants and one pound of raisins. Built to feed a crowd and keep for weeks.',
        leaveningNote: 'Original uses baking soda (10g) activated by sour milk — equivalent to about 2 tsp baking powder (8g) if using sweet milk.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Brown Sugar (Light)', amount: 453 },
          { name: 'Unsalted Butter', amount: 340 },
          { name: 'Buttermilk', amount: 480 },
          { name: 'Molasses', amount: 480 },
          { name: 'Whole Egg (large)', amount: 250 },
          { name: 'Baking Soda', amount: 10 },
          { name: 'Cloves', amount: 5 },
          { name: 'Allspice', amount: 5 },
          { name: 'Cinnamon', amount: 5 },
          { name: 'Nutmeg', amount: 5 },
          { name: 'All-Purpose Flour', amount: 1360 },
          { name: 'Dried Currants', amount: 907 },
          { name: 'Raisins', amount: 453 },
        ],
      },
      {
        group: 'Fruit Cakes',
        name: 'Plum Cake',
        emoji: '🫐',
        source: 'New York Cake Book, 1904',
        description: 'An English-style plum cake — candied citron, orange peel, currants, and sweet almonds in a rich butter batter. A proper Victorian celebration cake.',
        leaveningNote: 'No leavening — beaten egg foam provides structure. Bake low and slow, about 1½ hours.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original' },
          { name: 'Salt', amount: 4, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'All-Purpose Flour', amount: 680 },
          { name: 'Unsalted Butter', amount: 453 },
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Dried Currants', amount: 227 },
          { name: 'Candied Citron Peel', amount: 227 },
          { name: 'Orange Zest', amount: 15 },
          { name: 'Almonds (sliced)', amount: 57 },
          { name: 'Allspice', amount: 3 },
          { name: 'Cinnamon', amount: 3 },
          { name: 'Whole Egg (large)', amount: 500 },
        ],
      },
      {
        group: 'Gingerbread',
        name: 'Soft Gingerbread (Molasses)',
        emoji: '🫚',
        source: 'New York Cake Book, 1904',
        description: 'A deep, dark, moist gingerbread — molasses, butter, sour milk, and two tablespoons of fresh ginger. Baked in a deep pan.',
        leaveningNote: 'Original uses baking soda (10g) activated by sour milk. Use buttermilk to preserve the original chemistry, or 2 tsp baking powder (8g) with sweet milk.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 4, note: 'Not in original' },
          { name: 'Cinnamon', amount: 4, note: 'Not in original — classic pairing' },
        ],
        ingredients: [
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Molasses', amount: 480 },
          { name: 'Ginger (ground)', amount: 14 },
          { name: 'All-Purpose Flour', amount: 240 },
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'Baking Soda', amount: 10 },
          { name: 'Buttermilk', amount: 240 },
          { name: 'Lemon Zest', amount: 5 },
        ],
      },
      {
        group: 'Gingerbread',
        name: 'Spiced Gingerbread (Hard)',
        emoji: '🫚',
        source: 'New York Cake Book, 1904',
        description: 'A firm gingerbread rolled thin and baked on sheets — the original gingerbread cookie/cake, spiced with ginger, cloves, coriander, and caraway.',
        leaveningNote: 'Original uses cream of tartar (3g) + baking soda (2g) — equivalent to 1 tsp baking powder (4g).',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Whole Egg (large)', amount: 250 },
          { name: 'Whole Milk', amount: 45 },
          { name: 'Cream of Tartar', amount: 3 },
          { name: 'Baking Soda', amount: 2 },
          { name: 'Ginger (ground)', amount: 12 },
          { name: 'All-Purpose Flour', amount: 453 },
          { name: 'Cloves', amount: 5 },
          { name: 'Nutmeg', amount: 3 },
          { name: 'Cinnamon', amount: 5 },
        ],
      },
      {
        group: 'Spice Cakes',
        name: 'Currant Spice Cake',
        emoji: '🍇',
        source: 'New York Cake Book, 1904',
        description: 'A satisfying spiced currant cake — cinnamon, baking soda, and lemon in a simple butter batter. Quick to make and keeps well.',
        leaveningNote: 'Original uses baking soda (2g) activated by the lemon juice in the recipe.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 4, note: 'Not in original' },
          { name: 'Nutmeg', amount: 2, note: 'Not in original — pairs well with currant' },
        ],
        ingredients: [
          { name: 'All-Purpose Flour', amount: 453 },
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Granulated Sugar', amount: 340 },
          { name: 'Dried Currants', amount: 227 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Cinnamon', amount: 5 },
          { name: 'Baking Soda', amount: 2 },
          { name: 'Lemon Juice', amount: 20 },
          { name: 'Lemon Zest', amount: 5 },
        ],
      },
      {
        group: 'Spice Cakes',
        name: 'Spice Cakes (Molasses & Caraway)',
        emoji: '🌿',
        source: 'New York Cake Book, 1904',
        description: 'Small spiced cakes flavored with caraway and coriander seeds in a molasses and butter base — rolled thin and cut into rounds.',
        leaveningNote: 'Original uses baking soda (5g) activated by warm water.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Granulated Sugar', amount: 200 },
          { name: 'Molasses', amount: 200 },
          { name: 'Cinnamon', amount: 5 },
          { name: 'Ginger (ground)', amount: 5 },
          { name: 'Nutmeg', amount: 3 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'All-Purpose Flour', amount: 360 },
        ],
      },
      {
        group: 'Spice Cakes',
        name: 'Coffee Cake (Dark Fruit)',
        emoji: '☕',
        source: 'New York Cake Book, 1904',
        description: 'A rich dark cake made with strong brewed coffee, molasses, and two-and-a-half pounds of currants and citron. Bakes for a full hour at low temperature.',
        leaveningNote: 'Original uses baking soda (10g) dissolved in warm coffee.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 5, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Brown Sugar (Dark)', amount: 255 },
          { name: 'Unsalted Butter', amount: 397 },
          { name: 'Molasses', amount: 480 },
          { name: 'All-Purpose Flour', amount: 680 },
          { name: 'Dried Currants', amount: 680 },
          { name: 'Candied Citron Peel', amount: 453 },
          { name: 'Mace', amount: 6 },
          { name: 'Cinnamon', amount: 6 },
          { name: 'Ginger (ground)', amount: 6 },
          { name: 'Cloves', amount: 3 },
          { name: 'Allspice', amount: 3 },
          { name: 'Baking Soda', amount: 10 },
        ],
      },
      {
        group: 'Soaked Cakes',
        name: 'Rum Cake',
        emoji: '🥃',
        source: 'Classic Caribbean/American recipe',
        description: 'A rich butter Bundt cake soaked while still hot in a rum-butter-sugar glaze. The glaze seeps into every crumb, making it extraordinarily moist and deeply flavored. Gets better the next day.',
        leaveningNote: 'Uses baking powder (8g) and baking soda (3g). The soak is poured over the hot cake immediately after coming out of the oven — do not wait.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Granulated Sugar', amount: 300 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'Vanilla Extract', amount: 10 },
          { name: 'All-Purpose Flour', amount: 300 },
          { name: 'Baking Powder', amount: 8 },
          { name: 'Baking Soda', amount: 3 },
          { name: 'Salt', amount: 3 },
          { name: 'Sour Cream', amount: 240 },
          { name: 'Dark Rum', amount: 120 },
          { name: 'Brown Sugar (Light)', amount: 100 },
        ],
      },
      {
        group: 'Soaked Cakes',
        name: 'Tres Leches Cake',
        emoji: '🥛',
        source: 'Classic Latin American recipe',
        description: 'A light sponge cake soaked to saturation in three milks: evaporated, sweetened condensed, and heavy cream. The result is a completely unique texture — wet and creamy yet still holding its shape. Finished with whipped cream.',
        leaveningNote: 'Uses baking powder (6g) in the sponge. The sponge must be porous enough to absorb the milk soak — do not overbake or it will not absorb properly.',
        ingredients: [
          { name: 'Whole Egg (large)', amount: 300 },
          { name: 'Granulated Sugar', amount: 200 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'All-Purpose Flour', amount: 180 },
          { name: 'Baking Powder', amount: 6 },
          { name: 'Whole Milk', amount: 60 },
          { name: 'Evaporated Milk', amount: 340 },
          { name: 'Condensed Milk', amount: 300 },
          { name: 'Heavy Cream', amount: 120 },
        ],
      },
      {
        group: 'Soaked Cakes',
        name: 'Lemon Drizzle Cake',
        emoji: '🍋',
        source: 'Classic British recipe',
        description: 'A simple all-in-one butter cake baked in a loaf tin, then immediately pierced all over and drenched with a tart lemon-sugar syrup while hot. The syrup soaks in and forms a crackly crust on top. Quintessentially British.',
        leaveningNote: 'Uses baking powder (8g). The drizzle goes on while the cake is still hot and in the tin — this is when the syrup soaks in most effectively.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 225 },
          { name: 'Granulated Sugar', amount: 225 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'All-Purpose Flour', amount: 225 },
          { name: 'Baking Powder', amount: 8 },
          { name: 'Lemon Zest', amount: 8 },
          { name: 'Lemon Juice', amount: 60 },
          { name: 'Powdered Sugar', amount: 100 },
        ],
      },
    ],
  },

  {
    id: 'small',
    name: 'Small Cakes',
    emoji: '🧁',
    category: 'Classic',
    description: 'Individual cakes baked in cups or small tins — the original cupcakes and tea cakes.',
    characteristics: ['Individual', 'Small', 'Quick to bake'],
    examples: ['Cup Cake', 'Coconut Cakes', 'Almond Macaroons'],
    scienceNote: 'Smaller mass means faster heat penetration — small cakes bake more evenly and develop a better crust-to-crumb ratio.',
    color: 'from-pink-400 to-rose-500',
    baseFormula: [
      { name: 'Granulated Sugar', amount: 200 },
      { name: 'Unsalted Butter', amount: 113 },
      { name: 'Whole Egg (large)', amount: 100 },
      { name: 'Whole Milk', amount: 80 },
      { name: 'All-Purpose Flour', amount: 180 },
      { name: 'Baking Powder', amount: 5 },
    ],
    recipes: [
      {
        group: 'Cup Cakes',
        name: 'Cup Cake No. 1 (Almond)',
        emoji: '🌸',
        source: 'New York Cake Book, 1904',
        description: 'The original American cupcake — baked in cups, flavored with almond, with baking powder stirred in just before going into the oven.',
        leaveningNote: 'Original uses baking powder (5g) added at the last moment — an early use of baking powder in American baking.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 4, note: 'Not in original — adds warmth alongside almond' },
          { name: 'Salt', amount: 2, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 400 },
          { name: 'Unsalted Butter', amount: 227 },
          { name: 'Whole Egg (large)', amount: 200 },
          { name: 'All-Purpose Flour', amount: 360 },
          { name: 'Baking Powder', amount: 5 },
          { name: 'Almond Extract', amount: 4 },
        ],
      },
      {
        group: 'Cup Cakes',
        name: 'Cup Cake No. 2 (Lemon)',
        emoji: '🍋',
        source: 'New York Cake Book, 1904',
        description: 'A large-batch lemon cup cake — rose water or lemon essence, baked in cups or pans. Slightly denser than the first version.',
        leaveningNote: 'Original uses baking soda (5g) dissolved in milk — equivalent to about 2 tsp baking powder (8g) with sweet milk.',
        optionalAdditions: [
          { name: 'Lemon Zest', amount: 5, note: 'Not in original — enhances the lemon flavor' },
          { name: 'Salt', amount: 3, note: 'Not in original' },
        ],
        ingredients: [
          { name: 'Granulated Sugar', amount: 600 },
          { name: 'Unsalted Butter', amount: 340 },
          { name: 'Whole Egg (large)', amount: 150 },
          { name: 'All-Purpose Flour', amount: 720 },
          { name: 'Lemon Extract', amount: 5 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'Whole Milk', amount: 240 },
          { name: 'Cream of Tartar', amount: 9 },
        ],
      },
      {
        group: 'Coconut Tea Cakes',
        name: 'Coconut Drops (Small Cakes)',
        emoji: '🥥',
        source: 'New York Cake Book, 1904',
        description: 'Tiny coconut drop cakes — grated coconut, beaten egg whites, and sugar. Baked on buttered plates until golden. Chewy, sweet, and addictive.',
        leaveningNote: 'No leavening — egg whites and coconut provide all structure.',
        optionalAdditions: [
          { name: 'Vanilla Extract', amount: 3, note: 'Not in original' },
          { name: 'Almond Extract', amount: 2, note: 'Not in original — classic pairing' },
        ],
        ingredients: [
          { name: 'Shredded Coconut', amount: 453 },
          { name: 'Granulated Sugar', amount: 453 },
          { name: 'Egg White', amount: 180 },
        ],
      },
      {
        group: 'French Petits Fours',
        name: 'Madeleines',
        emoji: '🐚',
        source: 'Classic French recipe',
        description: 'Small shell-shaped cakes made from a brown butter génoise batter rested overnight. The characteristic hump forms from the cold batter hitting a hot pan. Marcel Proust\'s madeleine in À la recherche du temps perdu.',
        leaveningNote: 'Uses baking powder (3g). Resting the batter cold for at least 1 hour (ideally overnight) is essential — this thermal shock creates the signature hump.',
        ingredients: [
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'Granulated Sugar', amount: 100 },
          { name: 'Vanilla Extract', amount: 3 },
          { name: 'Lemon Zest', amount: 3 },
          { name: 'All-Purpose Flour', amount: 100 },
          { name: 'Baking Powder', amount: 3 },
          { name: 'Unsalted Butter', amount: 90 },
          { name: 'Salt', amount: 1 },
        ],
      },
      {
        group: 'French Petits Fours',
        name: 'Financiers',
        emoji: '🟨',
        source: 'Classic French recipe',
        description: 'Small rectangular French cakes made with almond flour, browned butter, and egg whites — no yolks. Named for the financial district near their origin bakery. Crisp edges, moist chewy center.',
        leaveningNote: 'Uses baking powder (3g). Brown butter (beurre noisette) is the defining flavor — do not use plain melted butter.',
        ingredients: [
          { name: 'Almond Flour', amount: 100 },
          { name: 'Powdered Sugar', amount: 120 },
          { name: 'All-Purpose Flour', amount: 40 },
          { name: 'Baking Powder', amount: 3 },
          { name: 'Egg White', amount: 120 },
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Vanilla Extract', amount: 3 },
          { name: 'Salt', amount: 1 },
        ],
      },
      {
        group: 'French Petits Fours',
        name: 'Canelés de Bordeaux',
        emoji: '🕯️',
        source: 'Classic French recipe (Bordeaux)',
        description: 'A Bordeaux specialty — deep, dark caramelized crust encasing a soft, custardy, rum-and-vanilla interior. Baked in fluted copper molds. The contrast between the crunchy shell and the yielding center is extraordinary.',
        leaveningNote: 'No leavening — a pure custard batter. The batter must rest 24–48 hours in the fridge. Baked at 450°F for 15 minutes, then reduced to 375°F for 45 minutes.',
        ingredients: [
          { name: 'Whole Milk', amount: 480 },
          { name: 'Whole Egg (large)', amount: 100 },
          { name: 'Egg Yolk', amount: 80 },
          { name: 'Granulated Sugar', amount: 200 },
          { name: 'All-Purpose Flour', amount: 60 },
          { name: 'Unsalted Butter', amount: 28 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'Dark Rum', amount: 30 },
          { name: 'Salt', amount: 1 },
        ],
      },
      {
        group: 'American Small Cakes',
        name: 'Whoopie Pies',
        emoji: '🖤',
        source: 'Classic American recipe (New England/Pennsylvania)',
        description: 'Two soft, domed chocolate cake rounds sandwiched with marshmallow cream filling. Somewhere between a cookie and a cake. A New England and Pennsylvania Dutch classic — sold at farm stands and bakeries across the Northeast.',
        leaveningNote: 'Uses baking soda (5g) activated by the buttermilk. The soft, dome shape comes from a high-hydration batter dropped by the spoonful.',
        ingredients: [
          { name: 'Unsalted Butter', amount: 113 },
          { name: 'Granulated Sugar', amount: 200 },
          { name: 'Whole Egg (large)', amount: 50 },
          { name: 'Vanilla Extract', amount: 5 },
          { name: 'All-Purpose Flour', amount: 240 },
          { name: 'Cocoa Powder (Natural)', amount: 48 },
          { name: 'Baking Soda', amount: 5 },
          { name: 'Salt', amount: 3 },
          { name: 'Buttermilk', amount: 240 },
        ],
      },
    ],
  },
];
